variables:
  BUILD_IMAGE: gitlab-registry.aspera.us/devops/docker-aspera-builder:v0.4.0-rc.17

before_script:
  - npm install tslint

stages:
  - test

test:lint:
  stage: test
  image: ${BUILD_IMAGE}
  script:
    - cd packages/browser && npm run lint
