variables:
  BUILD_IMAGE: gitlab-registry.aspera.us/devops/docker-aspera-builder:v0.4.0-rc.17

stages:
  - test
  - deploy
  
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    
before_script:
  - npm install

test:
  stage: test
  image: ${BUILD_IMAGE}
  script:
    - npm test -- --watchAll=false

pages:
  stage: deploy
  image: ${BUILD_IMAGE}
  script:
    - npm run build
    - rm -rf public
    - mkdir -p public
    - cp -R build/* public/
  artifacts:
    paths:
    - public
