name: CI

on: [push, pull_request]

jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: |
          npm ci

      - name: Build
        run: |
          npm run build

      - name: Integration Tests
        run: |
          npm run test:headless

      - name: UI Tests
        run: |
          npm --prefix ui run test

      - name: Lint Tests
        run: |
          npm run lint
