name: Documentation

on:
  push:
    tags:
      - 'v*'

jobs:
  Documentation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 18 ]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: |
          npm ci

      - name: Build Docs
        run: |
          npm run build
          npm run docs

      - name: Deploy
        uses: github/pages-deploy-action@v2
        with:
          branch: gh-pages
          folder: dist/docs
