name: Documentation

on:
  push:
    tags:
      - 'v*'

jobs:
  Documentation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm ci

      - name: Build Docs
        run: |
          npm run build
          npm run docs

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.2.2
        with:
          branch: gh-pages
          folder: dist/docs
