name: Publish to NPM

on:
  push:
    tags:
      - 'v*'

jobs:
  Publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 18 ]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: |
          npm ci

      - name: Build
        run: |
          npm run build

      - name: Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          access: public
          token: ${{ secrets.NPM_TOKEN }}
