name: Whitesource Security Scan

on:
  push:
    branches: [ whitesource ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run Whitesource Action
      uses: TheAxZim/Whitesource-Scan-Action@v1.0.0
      with:
        wssURL: https://ibmets.whitesourcesoftware.com/agent
        apiKey: ${{ secrets.WSS_API_KEY }}
        productName: ${{ secrets.WSS_PRODUCT_NAME }}
        projectName: aspera-connect-sdk-js
